/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#include "stm32f4xx_hal.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
N_NIMCALL(void, main_init)(void);
N_NIMCALL(void, LED1_tick)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);
void PreMainInner(void) {
	systemInit000();
	mainDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

int main(void) {
	NimMain();
	return 0;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	main_init();
	{
		while (1) {
			LED1_tick();
			HAL_Delay(((NU32) 1000));
		}
	}
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
}

